/**
 * Agent Harness 登记目录（authored half of agent-harness/registry.json）
 *
 * 这里是**人工维护**的部分：身份、责任归属、成熟度、类型化关系、作用域。
 * 指纹、行列号、摘要与 effective 状态是**计算得出**的，由
 * `node scripts/agent-harness-check.mjs --reconcile` 写入 registry.json，
 * 不要手写。
 *
 * 规则见 agent-harness/rules/objects.md（身份与标记）
 *   与 agent-harness/rules/governance.md（状态、关系、复核）。
 *
 * 变更目录必须走显式动作：新增或删除对象属于架构变更，需要一次复核记录。
 */

/** 说明：`blocks` 的 `{ at: "start" | "acceptance" }` 决定阻断的是开始还是验收。 */
const blocks = (at, ids) => ids.map((id) => ({ id, at }));

/** 来源对象：尚未采用分块标记的上位材料，按文件级来源对象绑定版本。 */
export const sources = {
  "SRC-DISC-2026-09-14": {
    path: "AGENT-REFORM-DISCUSSION-2026-09-14.md",
    kind: "discussion",
    role: "解释来源与事实边界；不作为规范条文",
    refs: ["P01", "P03", "P04", "P06"],
  },
  "SRC-ARCH-2026-09-15": {
    path: "docs/agent-architecture.md",
    kind: "architecture-definition",
    role: "上位架构决定；模块、组件、工具身份由它派生",
    refs: ["P01", "P02", "P03"],
  },
  "SRC-ARCH-REPO": {
    path: "ARCHITECTURE.md",
    kind: "implementation-facts",
    role: "当前实现事实与边界",
    refs: ["P04"],
  },
  "SRC-ROADMAP-REPO": {
    path: "ROADMAP.md",
    kind: "version-roadmap",
    role: "版本排期唯一来源；本体系不重复版本承诺",
    refs: ["P01"],
  },
};

/** 托管文件 → 文件级对象 ID。文件级对象承接所有子对象块之外的正文。 */
export const files = {
  "modules/README.md": "README-MODULES",
  "contracts/README.md": "README-CONTRACTS",
  "tools/README.md": "README-TOOLS",
  "flows/README.md": "README-FLOWS",

  "registry.json": "FILE-REGISTRY",
  "README.md": "P01",
  "contracts/K01-request-identity.md": "K01",
  "contracts/K02-run-lifecycle.md": "K02",
  "contracts/K03-instruction-revision.md": "K03",
  "contracts/K04-provider-capability.md": "K04",
  "contracts/K05-authorization-and-confirmation.md": "K05",
  "contracts/K06-budget-ledger.md": "K06",
  "contracts/K07-context-assembly.md": "K07",
  "contracts/K08-compaction-and-memory.md": "K08",
  "contracts/K09-web-authorization.md": "K09",
  "contracts/K10-tool-surface.md": "K10",
  "contracts/K11-dual-path-search.md": "K11",
  "contracts/K12-native-search-subrequest.md": "K12",
  "contracts/K13-web-reading-window.md": "K13",
  "contracts/K14-evidence-and-provenance.md": "K14",
  "contracts/K15-delivery-result.md": "K15",
  "contracts/K16-verification-report.md": "K16",
  "contracts/K17-audit-events.md": "K17",
  "contracts/K18-mcp-transport.md": "K18",
  "decisions/README.md": "FILE-DECISIONS",
  "flows/L01-conversation-and-revision.md": "L01",
  "flows/L02-web-retrieval.md": "L02",
  "flows/L03-editing-and-application.md": "L03",
  "flows/L04-format-preservation.md": "L04",
  "flows/L05-context-and-memory.md": "L05",
  "flows/L06-delegation.md": "L06",
  "implementation/D01-trustworthy-baseline.md": "D01",
  "implementation/D02-protocol-and-recovery.md": "D02",
  "implementation/D03-session-permission-context.md": "D03",
  "implementation/D04-dual-path-search.md": "D04",
  "implementation/D05-document-tasks-and-delivery.md": "D05",
  "implementation/README.md": "FILE-IMPLEMENTATION",
  "modules/eval-system.md": "FILE-EVAL-SYSTEM",
  "modules/m01-session-and-run.md": "M01",
  "modules/m02-permission-and-side-effects.md": "M02",
  "modules/m03-context-and-memory.md": "M03",
  "modules/m04-model-gateway.md": "M04",
  "modules/m05-agent-execution.md": "M05",
  "modules/m06-tools-and-connectors.md": "M06",
  "modules/m07-retrieval-and-evidence.md": "M07",
  "modules/m08-verification-and-delivery.md": "M08",
  "modules/m09-audit-and-diagnostics.md": "M09",
  "requirements/current-baseline.md": "P04",
  "requirements/open-items.md": "P05",
  "requirements/requirements.md": "P06",
  "rules/governance.md": "P03",
  "rules/objects.md": "P02",
  "testing/acceptance-matrix.md": "V03",
  "testing/evidence.md": "V01",
  "tests/legacy-batch-plan.md": "D06",
  "tools/app_context_read.md": "T02",
  "tools/capabilities_read.md": "T03",
  "tools/doc_extract_citations.md": "T26",
  "tools/doc_normalize_markdown.md": "T25",
  "tools/fs_export.md": "T22",
  "tools/fs_import_to_vault.md": "T21",
  "tools/fs_read_authorized_folder.md": "T23",
  "tools/fs_write_authorized_export.md": "T24",
  "tools/get_backlinks.md": "T09",
  "tools/get_context_packets.md": "T10",
  "tools/get_outline.md": "T08",
  "tools/get_regulation.md": "T30",
  "tools/git_read_diff.md": "T18",
  "tools/git_read_log.md": "T19",
  "tools/git_read_status.md": "T17",
  "tools/git_write_commit.md": "T27",
  "tools/insert_text_at_cursor.md": "T15",
  "tools/list_vault.md": "T07",
  "tools/memory_read.md": "T13",
  "tools/memory_write.md": "T14",
  "tools/read_note.md": "T06",
  "tools/replace_selection.md": "T16",
  "tools/scheduled_task_create.md": "T32",
  "tools/scheduled_task_delete.md": "T34",
  "tools/scheduled_task_list.md": "T33",
  "tools/search_hybrid.md": "T05",
  "tools/search_keyword.md": "T29",
  "tools/search_semantic.md": "T28",
  "tools/secret_exists.md": "T20",
  "tools/skills_list.md": "T04",
  "tools/spawn_subagent.md": "T31",
  "tools/system_time_now.md": "T01",
  "tools/vault_asset_write.md": "T38",
  "tools/vault_create_note.md": "T35",
  "tools/vault_delete_to_trash.md": "T37",
  "tools/vault_rename_move.md": "T36",
  "tools/vault_version_list.md": "T39",
  "tools/web_fetch.md": "T12",
  "tools/web_search.md": "T11",
};

/**
 * 单对象文件的文件级容器。容器与对象共用 ID，但它们是两个不同的登记身份：
 * 容器承接外围正文（前言、公共说明），对象承接正式定义正文。
 * 权威 JSON 用 `<ID>#file` 区分容器，用 `<ID>` 表示定义。
 */
export const fileContainers = {
  "README-MODULES": "modules/README.md",
  "README-CONTRACTS": "contracts/README.md",
  "README-TOOLS": "tools/README.md",
  "README-FLOWS": "flows/README.md",

  "FILE-REGISTRY": "registry.json",
  "FILE-DECISIONS": "decisions/README.md",
  "FILE-IMPLEMENTATION": "implementation/README.md",
  "FILE-EVAL-SYSTEM": "modules/eval-system.md",
  D01: "implementation/D01-trustworthy-baseline.md",
  D02: "implementation/D02-protocol-and-recovery.md",
  D03: "implementation/D03-session-permission-context.md",
  D04: "implementation/D04-dual-path-search.md",
  D05: "implementation/D05-document-tasks-and-delivery.md",
  D06: "tests/legacy-batch-plan.md",
  "FILE-IMPLEMENTATION": "implementation/README.md",
  K01: "contracts/K01-request-identity.md",
  K02: "contracts/K02-run-lifecycle.md",
  K03: "contracts/K03-instruction-revision.md",
  K04: "contracts/K04-provider-capability.md",
  K05: "contracts/K05-authorization-and-confirmation.md",
  K06: "contracts/K06-budget-ledger.md",
  K07: "contracts/K07-context-assembly.md",
  K08: "contracts/K08-compaction-and-memory.md",
  K09: "contracts/K09-web-authorization.md",
  K10: "contracts/K10-tool-surface.md",
  K11: "contracts/K11-dual-path-search.md",
  K12: "contracts/K12-native-search-subrequest.md",
  K13: "contracts/K13-web-reading-window.md",
  K14: "contracts/K14-evidence-and-provenance.md",
  K15: "contracts/K15-delivery-result.md",
  K16: "contracts/K16-verification-report.md",
  K17: "contracts/K17-audit-events.md",
  K18: "contracts/K18-mcp-transport.md",
  L01: "flows/L01-conversation-and-revision.md",
  L02: "flows/L02-web-retrieval.md",
  L03: "flows/L03-editing-and-application.md",
  L04: "flows/L04-format-preservation.md",
  L05: "flows/L05-context-and-memory.md",
  L06: "flows/L06-delegation.md",
  P01: "README.md",
  T01: "tools/system_time_now.md",
  T02: "tools/app_context_read.md",
  T03: "tools/capabilities_read.md",
  T04: "tools/skills_list.md",
  T05: "tools/search_hybrid.md",
  T06: "tools/read_note.md",
  T07: "tools/list_vault.md",
  T08: "tools/get_outline.md",
  T09: "tools/get_backlinks.md",
  T10: "tools/get_context_packets.md",
  T11: "tools/web_search.md",
  T12: "tools/web_fetch.md",
  T13: "tools/memory_read.md",
  T14: "tools/memory_write.md",
  T15: "tools/insert_text_at_cursor.md",
  T16: "tools/replace_selection.md",
  T17: "tools/git_read_status.md",
  T18: "tools/git_read_diff.md",
  T19: "tools/git_read_log.md",
  T20: "tools/secret_exists.md",
  T21: "tools/fs_import_to_vault.md",
  T22: "tools/fs_export.md",
  T23: "tools/fs_read_authorized_folder.md",
  T24: "tools/fs_write_authorized_export.md",
  T25: "tools/doc_normalize_markdown.md",
  T26: "tools/doc_extract_citations.md",
  T27: "tools/git_write_commit.md",
  T28: "tools/search_semantic.md",
  T29: "tools/search_keyword.md",
  T30: "tools/get_regulation.md",
  T31: "tools/spawn_subagent.md",
  T32: "tools/scheduled_task_create.md",
  T33: "tools/scheduled_task_list.md",
  T34: "tools/scheduled_task_delete.md",
  T35: "tools/vault_create_note.md",
  T36: "tools/vault_rename_move.md",
  T37: "tools/vault_delete_to_trash.md",
  T38: "tools/vault_asset_write.md",
  T39: "tools/vault_version_list.md",
};

/**
 * 对象目录。键是对象 ID。
 *
 * 字段：
 *   kind          module | component | eval | tool | contract | flow | evidence | work | decision | rules | issue | test
 *   name          稳定英文标识（工具名、合同短名）；工具与合同必填
 *   title         中文标题
 *   owner         责任对象 ID（工作是模块或组件 ID；模块是自身）
 *   maturity      registered | draft | defined | superseded | retired
 *   definition    标准定义位置 { file, anchor }；maturity=registered 时必须省略
 *   implementation / verification / work   状态维度
 *   scope         工作包引用到的需求（N*）与对象（*）
 *   relations     implements | consumes | verifies | depends_on | blocks | supersedes
 *   note          检查器不做语义判断，但要求写明该条登记的判断依据
 */
export const objects = {
  "README-MODULES": {
    kind: "rules",
    name: "readme-modules",
    title: "modules/README.md 目录索引",
    owner: "P03",
    maturity: "draft",
    definition: { file: "modules/README.md", anchor: "README-MODULES" },
    note: "目录索引容器：登记子对象身份，不承载正式定义",
  },
  "README-CONTRACTS": {
    kind: "rules",
    name: "readme-contracts",
    title: "contracts/README.md 目录索引",
    owner: "P03",
    maturity: "draft",
    definition: { file: "contracts/README.md", anchor: "README-CONTRACTS" },
    note: "目录索引容器：登记子对象身份，不承载正式定义",
  },
  "README-TOOLS": {
    kind: "rules",
    name: "readme-tools",
    title: "tools/README.md 目录索引",
    owner: "P03",
    maturity: "draft",
    definition: { file: "tools/README.md", anchor: "README-TOOLS" },
    note: "目录索引容器：登记子对象身份，不承载正式定义",
  },
  "README-FLOWS": {
    kind: "rules",
    name: "readme-flows",
    title: "flows/README.md 目录索引",
    owner: "P03",
    maturity: "draft",
    definition: { file: "flows/README.md", anchor: "README-FLOWS" },
    note: "目录索引容器：登记子对象身份，不承载正式定义",
  },

  // ── P01 入口 ────────────────────────────────────────────────
  P01: {
    kind: "rules",
    name: "harness-entry",
    title: "Agent Harness 文档体系入口",
    owner: "P01",
    maturity: "defined",
    definition: { file: "README.md", anchor: "P01" },
    note: "入口、阅读路径与三批交付状态",
  },

  // ── P02/P03/P04/P05/P06 规则与需求 ─────────────────────────
  P02: {
    kind: "rules",
    name: "object-identity-and-markers",
    title: "对象、标记与引用规则",
    owner: "P02",
    maturity: "defined",
    definition: { file: "rules/objects.md", anchor: "P02" },
    note: "检查器的实现依据；身份、标记、指纹与关系方向在此固定",
  },
  P03: {
    kind: "rules",
    name: "governance",
    title: "治理规则：权威、状态、变更、复核与阻断",
    owner: "P03",
    maturity: "defined",
    definition: { file: "rules/governance.md", anchor: "P03" },
    note: "状态四维、关系模型、变更分类与独立复核规则",
  },
  P04: {
    kind: "rules",
    name: "current-baseline",
    title: "当前基线与未决问题",
    owner: "P04",
    maturity: "defined",
    definition: { file: "requirements/current-baseline.md", anchor: "P04" },
    consumes: ["P05"],
    note: "源码事实与 Q* 未决事项的唯一位置",
  },
  P05: {
    kind: "rules",
    name: "open-items",
    title: "缺口与未决项",
    owner: "P05",
    maturity: "defined",
    definition: { file: "requirements/open-items.md", anchor: "P05" },
    note: "G* 缺口与其工作包对应",
  },
  P06: {
    kind: "rules",
    name: "requirements",
    title: "需求与边界",
    owner: "P06",
    maturity: "defined",
    definition: { file: "requirements/requirements.md", anchor: "P06" },
    note: "N01–N23 需求身份；工作包作用域引用的来源",
  },

  P07: {
    kind: "rules",
    name: "planned-and-entry-points",
    title: "协议入口与 Planned 占位登记",
    owner: "P05",
    maturity: "defined",
    definition: { file: "tools/README.md", anchor: "P07" },
    consumes: ["P03", "P05"],
    note: "登记不进入 39 个业务工具数的入口与 Planned 占位；Planned 不暴露",
  },

  // ── M01–M09 模块 ───────────────────────────────────────────
  M01: {
    kind: "module",
    name: "session-and-run",
    title: "M1 会话与 Run 管理",
    owner: "M01",
    maturity: "draft",
    definition: { file: "modules/m01-session-and-run.md", anchor: "M01" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["N01", "N05", "N16"],
    consumes: ["K01", "K02", "K03", "K04"],
  },
  M02: {
    kind: "module",
    name: "permission-and-side-effects",
    title: "M2 权限与受控副作用",
    owner: "M02",
    maturity: "draft",
    definition: {
      file: "modules/m02-permission-and-side-effects.md",
      anchor: "M02",
    },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["N03", "N12", "N13"],
    consumes: ["K05", "K06", "K16"],
  },
  M03: {
    kind: "module",
    name: "context-and-memory",
    title: "M3 上下文与记忆",
    owner: "M03",
    maturity: "draft",
    definition: { file: "modules/m03-context-and-memory.md", anchor: "M03" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["N05", "N14"],
    consumes: ["K07", "K08"],
  },
  M04: {
    kind: "module",
    name: "model-gateway",
    title: "M4 模型网关",
    owner: "M04",
    maturity: "draft",
    definition: { file: "modules/m04-model-gateway.md", anchor: "M04" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["N09", "N17", "N20"],
    consumes: ["K04", "K12"],
  },
  M05: {
    kind: "module",
    name: "agent-execution",
    title: "M5 Agent 执行控制",
    owner: "M05",
    maturity: "draft",
    definition: { file: "modules/m05-agent-execution.md", anchor: "M05" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["N15", "N16"],
    consumes: ["K06", "K17"],
  },
  M06: {
    kind: "module",
    name: "tools-and-connectors",
    title: "M6 工具与连接器",
    owner: "M06",
    maturity: "draft",
    definition: { file: "modules/m06-tools-and-connectors.md", anchor: "M06" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["N19"],
    consumes: ["K05", "K10", "K18"],
  },
  M07: {
    kind: "module",
    name: "retrieval-and-evidence",
    title: "M7 检索与证据",
    owner: "M07",
    maturity: "draft",
    definition: {
      file: "modules/m07-retrieval-and-evidence.md",
      anchor: "M07",
    },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["N06", "N07", "N08", "N10"],
    consumes: ["K09", "K10", "K11", "K12", "K13"],
  },
  M08: {
    kind: "module",
    name: "verification-and-delivery",
    title: "M8 验证与交付",
    owner: "M08",
    maturity: "draft",
    definition: {
      file: "modules/m08-verification-and-delivery.md",
      anchor: "M08",
    },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["N02", "N04", "N11", "N17"],
    consumes: ["K14", "K15", "K16"],
  },
  M09: {
    kind: "module",
    name: "audit-and-diagnostics",
    title: "M9 审计与诊断",
    owner: "M09",
    maturity: "draft",
    definition: { file: "modules/m09-audit-and-diagnostics.md", anchor: "M09" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["N18"],
    consumes: ["K17"],
  },

  // ── C01–C27 组件 ───────────────────────────────────────────
  C01: {
    kind: "component",
    name: "request-and-reference-binding",
    title: "C01 请求与引用绑定",
    owner: "M01",
    maturity: "draft",
    definition: { file: "modules/m01-session-and-run.md", anchor: "C01" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K01"],
  },
  C02: {
    kind: "component",
    name: "session-and-run-state",
    title: "C02 会话与运行状态",
    owner: "M01",
    maturity: "draft",
    definition: { file: "modules/m01-session-and-run.md", anchor: "C02" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K02"],
  },
  C03: {
    kind: "component",
    name: "instruction-revision-and-cancel",
    title: "C03 指令修订与取消协调",
    owner: "M01",
    maturity: "draft",
    definition: { file: "modules/m01-session-and-run.md", anchor: "C03" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K03"],
    depends_on: ["C01", "C02"],
  },
  C04: {
    kind: "component",
    name: "authorization-and-egress",
    title: "C04 授权与外发策略",
    owner: "M02",
    maturity: "draft",
    definition: {
      file: "modules/m02-permission-and-side-effects.md",
      anchor: "C04",
    },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K05"],
    depends_on: ["C01"],
  },
  C05: {
    kind: "component",
    name: "change-freeze-and-confirmation",
    title: "C05 变更冻结与确认",
    owner: "M02",
    maturity: "draft",
    definition: {
      file: "modules/m02-permission-and-side-effects.md",
      anchor: "C05",
    },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K05", "K16"],
    depends_on: ["C04"],
  },
  C06: {
    kind: "component",
    name: "deterministic-side-effects",
    title: "C06 确定性副作用执行",
    owner: "M02",
    maturity: "draft",
    definition: {
      file: "modules/m02-permission-and-side-effects.md",
      anchor: "C06",
    },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K05"],
    depends_on: ["C05"],
  },
  C07: {
    kind: "component",
    name: "context-assembly",
    title: "C07 当前上下文装配",
    owner: "M03",
    maturity: "draft",
    definition: { file: "modules/m03-context-and-memory.md", anchor: "C07" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K07"],
  },
  C08: {
    kind: "component",
    name: "compaction-and-work-state",
    title: "C08 会话压缩与工作状态",
    owner: "M03",
    maturity: "draft",
    definition: { file: "modules/m03-context-and-memory.md", anchor: "C08" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K07", "K08"],
    depends_on: ["C07"],
  },
  C09: {
    kind: "component",
    name: "long-term-memory",
    title: "C09 长期记忆",
    owner: "M03",
    maturity: "draft",
    definition: { file: "modules/m03-context-and-memory.md", anchor: "C09" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K08"],
    depends_on: ["C04"],
  },
  C10: {
    kind: "component",
    name: "capability-and-routing",
    title: "C10 能力与路由",
    owner: "M04",
    maturity: "draft",
    definition: { file: "modules/m04-model-gateway.md", anchor: "C10" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K04"],
    note: "C10 按端点探针 native_search_support_for 已落地；现行适配器与 Available 分流见 K12 执行事实。已有机械 V03，verification 仍 none，不是 passed，不是 V05。",
  },
  C11: {
    kind: "component",
    name: "protocol-and-continuation",
    title: "C11 协议与续轮适配",
    owner: "M04",
    maturity: "draft",
    definition: { file: "modules/m04-model-gateway.md", anchor: "C11" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K04"],
    depends_on: ["C10"],
    note: "fixture 解析器在 native_search_subrequest.rs；流式主路径仍未保真搜索事件。verification 仍 none，不把本条标 passed，不关 G03。",
  },
  C12: {
    kind: "component",
    name: "call-execution-and-usage",
    title: "C12 调用执行与用量",
    owner: "M04",
    maturity: "draft",
    definition: { file: "modules/m04-model-gateway.md", anchor: "C12" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K04", "K06"],
    depends_on: ["C11"],
  },
  C13: {
    kind: "component",
    name: "loop-state-and-budget",
    title: "C13 循环状态与预算",
    owner: "M05",
    maturity: "draft",
    definition: { file: "modules/m05-agent-execution.md", anchor: "C13" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K06"],
  },
  C14: {
    kind: "component",
    name: "action-and-recovery",
    title: "C14 行动与恢复协调",
    owner: "M05",
    maturity: "draft",
    definition: { file: "modules/m05-agent-execution.md", anchor: "C14" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K16"],
    depends_on: ["C13", "C17"],
  },
  C15: {
    kind: "component",
    name: "subtask-coordination",
    title: "C15 子任务协调",
    owner: "M05",
    maturity: "draft",
    definition: { file: "modules/m05-agent-execution.md", anchor: "C15" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K16", "L06"],
    depends_on: ["C13", "C16"],
  },
  C16: {
    kind: "component",
    name: "tool-catalog-and-surface",
    title: "C16 工具目录、工具面与技能接入",
    owner: "M06",
    maturity: "draft",
    definition: { file: "modules/m06-tools-and-connectors.md", anchor: "C16" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K10"],
  },
  C17: {
    kind: "component",
    name: "dispatch-and-observation",
    title: "C17 调用派发与观察",
    owner: "M06",
    maturity: "draft",
    definition: { file: "modules/m06-tools-and-connectors.md", anchor: "C17" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K10", "K16"],
    depends_on: ["C16", "C04", "C13"],
  },
  C18: {
    kind: "component",
    name: "mcp-transport",
    title: "C18 MCP 连接与传输",
    owner: "M06",
    maturity: "draft",
    definition: { file: "modules/m06-tools-and-connectors.md", anchor: "C18" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K18"],
    depends_on: ["C04"],
  },
  C19: {
    kind: "component",
    name: "local-retrieval",
    title: "C19 本地检索",
    owner: "M07",
    maturity: "draft",
    definition: {
      file: "modules/m07-retrieval-and-evidence.md",
      anchor: "C19",
    },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K09"],
    depends_on: ["C04"],
  },
  C20: {
    kind: "component",
    name: "dual-path-web-search",
    title: "C20 双路网页搜索协调",
    owner: "M07",
    maturity: "draft",
    definition: {
      file: "modules/m07-retrieval-and-evidence.md",
      anchor: "C20",
    },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K11", "K12", "N07"],
    depends_on: ["C10", "C18", "C13", "C04"],
    note: "协调器已接入生产 web_search；原生可达性见 K12 执行事实。partial 不是 present（G02 仍 open，V04 缺）。机械 V03 不是验收，不关 G02。",
  },
  C21: {
    kind: "component",
    name: "web-reading-and-extraction",
    title: "C21 网页读取与提取",
    owner: "M07",
    maturity: "draft",
    definition: {
      file: "modules/m07-retrieval-and-evidence.md",
      anchor: "C21",
    },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K13"],
    depends_on: ["C04", "C18"],
  },
  C22: {
    kind: "component",
    name: "evidence-and-provenance",
    title: "C22 证据与出处管理",
    owner: "M07",
    maturity: "draft",
    definition: {
      file: "modules/m07-retrieval-and-evidence.md",
      anchor: "C22",
    },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K14"],
    depends_on: ["C19", "C21"],
  },
  C23: {
    kind: "component",
    name: "task-verification",
    title: "C23 任务验证",
    owner: "M08",
    maturity: "draft",
    definition: {
      file: "modules/m08-verification-and-delivery.md",
      anchor: "C23",
    },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K16"],
    depends_on: ["C22"],
  },
  C24: {
    kind: "component",
    name: "edit-candidate-and-diff",
    title: "C24 编辑候选与差异",
    owner: "M08",
    maturity: "draft",
    definition: {
      file: "modules/m08-verification-and-delivery.md",
      anchor: "C24",
    },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K16", "L03", "L04"],
    depends_on: ["C07", "C05"],
  },
  C25: {
    kind: "component",
    name: "final-publication",
    title: "C25 最终发布与 UI 投影",
    owner: "M08",
    maturity: "draft",
    definition: {
      file: "modules/m08-verification-and-delivery.md",
      anchor: "C25",
    },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["K15"],
    depends_on: ["C23", "C02"],
  },
  C26: {
    kind: "component",
    name: "boundary-events",
    title: "C26 安全边界事件",
    owner: "M09",
    maturity: "draft",
    definition: { file: "modules/m09-audit-and-diagnostics.md", anchor: "C26" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K17"],
  },
  C27: {
    kind: "component",
    name: "diagnostic-query",
    title: "C27 诊断查询与解释",
    owner: "M09",
    maturity: "draft",
    definition: { file: "modules/m09-audit-and-diagnostics.md", anchor: "C27" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["K17"],
    depends_on: ["C26"],
  },

  // ── E01–E03 评测系统 ───────────────────────────────────────
  E01: {
    kind: "eval",
    name: "eval-cases-and-criteria",
    title: "E01 案例与判据",
    owner: "M08",
    maturity: "draft",
    definition: { file: "modules/eval-system.md", anchor: "E01" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["V01", "V02"],
  },
  E02: {
    kind: "eval",
    name: "eval-execution-and-replay",
    title: "E02 执行与重放",
    owner: "M08",
    maturity: "draft",
    definition: { file: "modules/eval-system.md", anchor: "E02" },
    implementation: { state: "present" },
    verification: { state: "none" },
    implements: ["V03", "V04"],
    depends_on: ["E01"],
  },
  E03: {
    kind: "eval",
    name: "eval-scoring-and-calibration",
    title: "E03 评分与校准",
    owner: "M08",
    maturity: "defined",
    definition: { file: "modules/eval-system.md", anchor: "E03" },
    implementation: { state: "partial" },
    verification: { state: "none" },
    implements: ["V01", "V06", "V07"],
    depends_on: ["E01", "E02"],
  },

  // ── K01–K18 共享合同 ───────────────────────────────────────
  K01: {
    kind: "contract",
    name: "request-identity",
    title: "K01 请求身份与引用绑定",
    owner: "C01",
    maturity: "defined",
    definition: { file: "contracts/K01-request-identity.md", anchor: "K01" },
    applies_to: ["C01", "C03", "C07", "C22"],
  },
  K02: {
    kind: "contract",
    name: "run-lifecycle",
    title: "K02 Run 生命周期与任务结果分离",
    owner: "C02",
    maturity: "defined",
    definition: { file: "contracts/K02-run-lifecycle.md", anchor: "K02" },
    applies_to: ["C02", "C25", "C27"],
  },
  K03: {
    kind: "contract",
    name: "instruction-revision",
    title: "K03 输入修订与取消",
    owner: "C03",
    maturity: "defined",
    definition: {
      file: "contracts/K03-instruction-revision.md",
      anchor: "K03",
    },
    applies_to: ["C03", "C07", "C14", "C25"],
  },
  K04: {
    kind: "contract",
    name: "provider-capability",
    title: "K04 供应商能力状态与续轮保真",
    owner: "C10",
    maturity: "defined",
    definition: { file: "contracts/K04-provider-capability.md", anchor: "K04" },
    applies_to: ["C10", "C11", "C12", "C20"],
  },
  K05: {
    kind: "contract",
    name: "authorization-and-confirmation",
    title: "K05 授权范围与冻结确认",
    owner: "C04",
    maturity: "defined",
    definition: {
      file: "contracts/K05-authorization-and-confirmation.md",
      anchor: "K05",
    },
    applies_to: ["C04", "C05", "C06", "C17", "C20", "C24"],
  },
  K06: {
    kind: "contract",
    name: "budget-ledger",
    title: "K06 统一预算账本",
    owner: "C13",
    maturity: "defined",
    definition: { file: "contracts/K06-budget-ledger.md", anchor: "K06" },
    applies_to: ["C12", "C13", "C15", "C17", "C20", "C21"],
  },
  K07: {
    kind: "contract",
    name: "context-assembly",
    title: "K07 上下文装配与裁剪边界",
    owner: "C07",
    maturity: "defined",
    definition: { file: "contracts/K07-context-assembly.md", anchor: "K07" },
    applies_to: ["C07", "C08", "C11"],
  },
  K08: {
    kind: "contract",
    name: "compaction-and-memory",
    title: "K08 压缩覆盖与长期记忆条目",
    owner: "C08",
    maturity: "defined",
    definition: {
      file: "contracts/K08-compaction-and-memory.md",
      anchor: "K08",
    },
    applies_to: ["C08", "C09"],
  },
  K09: {
    kind: "contract",
    name: "web-authorization",
    title: "K09 联网授权与查询外发",
    owner: "C04",
    maturity: "defined",
    definition: { file: "contracts/K09-web-authorization.md", anchor: "K09" },
    applies_to: ["C04", "C19", "C20", "C21", "C15"],
  },
  K10: {
    kind: "contract",
    name: "tool-surface",
    title: "K10 工具面版本与派发观察",
    owner: "C16",
    maturity: "defined",
    definition: { file: "contracts/K10-tool-surface.md", anchor: "K10" },
    applies_to: ["C16", "C17", "C14"],
  },
  K11: {
    kind: "contract",
    name: "dual-path-search",
    title: "K11 双路搜索协调结果",
    owner: "C20",
    maturity: "defined",
    definition: { file: "contracts/K11-dual-path-search.md", anchor: "K11" },
    applies_to: ["C20", "C10", "C18", "C22", "C25"],
  },
  K12: {
    kind: "contract",
    name: "native-search-subrequest",
    title: "K12 原生搜索受控子请求",
    owner: "C20",
    maturity: "defined",
    definition: {
      file: "contracts/K12-native-search-subrequest.md",
      anchor: "K12",
    },
    applies_to: ["C20", "C11", "C12"],
    note: "生产登记 2 个适配器；C10 对这两模型 Available。搜索事件尚未进入网关流式路径。不是 V05，不关 G03。正文见执行事实段。",
  },
  K13: {
    kind: "contract",
    name: "web-reading-window",
    title: "K13 网页读取窗口与完整性",
    owner: "C21",
    maturity: "defined",
    definition: { file: "contracts/K13-web-reading-window.md", anchor: "K13" },
    applies_to: ["C21", "C22", "C15"],
  },
  K14: {
    kind: "contract",
    name: "evidence-and-provenance",
    title: "K14 证据身份、来源与支持关系",
    owner: "C22",
    maturity: "defined",
    definition: {
      file: "contracts/K14-evidence-and-provenance.md",
      anchor: "K14",
    },
    applies_to: ["C22", "C07", "C23", "C25"],
  },
  K15: {
    kind: "contract",
    name: "delivery-result",
    title: "K15 交付结果与用户可见表达",
    owner: "C25",
    maturity: "defined",
    definition: { file: "contracts/K15-delivery-result.md", anchor: "K15" },
    applies_to: ["C25", "C23", "C14"],
  },
  K16: {
    kind: "contract",
    name: "verification-report",
    title: "K16 验证报告与可恢复错误反馈",
    owner: "C23",
    maturity: "defined",
    definition: { file: "contracts/K16-verification-report.md", anchor: "K16" },
    applies_to: ["C23", "C14", "C17", "C24"],
  },
  K17: {
    kind: "contract",
    name: "audit-events",
    title: "K17 审计事件与诊断查询",
    owner: "C26",
    maturity: "defined",
    definition: { file: "contracts/K17-audit-events.md", anchor: "K17" },
    applies_to: ["C26", "C27", "C11", "C20", "C21"],
  },
  K18: {
    kind: "contract",
    name: "mcp-transport",
    title: "K18 MCP 传输与外部工具边界",
    owner: "C18",
    maturity: "defined",
    definition: { file: "contracts/K18-mcp-transport.md", anchor: "K18" },
    applies_to: ["C18", "C16", "C20", "C21"],
  },

  // ── L01–L06 链路 ───────────────────────────────────────────
  L01: {
    kind: "flow",
    name: "conversation-and-revision",
    title: "L01 对话与修订链路",
    owner: "M05",
    maturity: "defined",
    definition: {
      file: "flows/L01-conversation-and-revision.md",
      anchor: "L01",
    },
    implements: ["N01", "N05"],
    consumes: ["K01", "K02", "K03", "K07", "K08", "K15"],
  },
  L02: {
    kind: "flow",
    name: "web-retrieval",
    title: "L02 联网检索与核实链路",
    owner: "M07",
    maturity: "defined",
    definition: { file: "flows/L02-web-retrieval.md", anchor: "L02" },
    implements: ["N06", "N07", "N08", "N10", "N11"],
    consumes: ["K09", "K11", "K12", "K13", "K14", "K15"],
  },
  L03: {
    kind: "flow",
    name: "editing-and-application",
    title: "L03 编辑与候选应用链路",
    owner: "M08",
    maturity: "defined",
    definition: { file: "flows/L03-editing-and-application.md", anchor: "L03" },
    implements: ["N02", "N03"],
    consumes: ["K05", "K14", "K16"],
  },
  L04: {
    kind: "flow",
    name: "format-preservation",
    title: "L04 格式保持链路",
    owner: "M08",
    maturity: "defined",
    definition: { file: "flows/L04-format-preservation.md", anchor: "L04" },
    implements: ["N04"],
    consumes: ["K16"],
  },
  L05: {
    kind: "flow",
    name: "context-and-memory",
    title: "L05 上下文与记忆链路",
    owner: "M03",
    maturity: "defined",
    definition: { file: "flows/L05-context-and-memory.md", anchor: "L05" },
    implements: ["N14"],
    consumes: ["K03", "K07", "K08"],
  },
  L06: {
    kind: "flow",
    name: "delegation",
    title: "L06 委派链路",
    owner: "M05",
    maturity: "defined",
    definition: { file: "flows/L06-delegation.md", anchor: "L06" },
    implements: ["N16"],
    consumes: ["K06", "K10", "K14", "K16"],
  },

  // ── V01–V08 证据与验收判据 ────────────────────────────────
  V01: {
    kind: "evidence",
    name: "evidence-categories",
    title: "V01 证据用途分类与组合要求",
    owner: "M08",
    maturity: "defined",
    definition: { file: "testing/evidence.md", anchor: "V01" },
  },
  V02: {
    kind: "evidence",
    name: "invariants-and-counterexamples",
    title: "V02 不变量、合法案例与违例案例登记",
    owner: "M08",
    maturity: "defined",
    definition: { file: "testing/evidence.md", anchor: "V02" },
  },
  V03: {
    kind: "evidence",
    name: "deterministic-cases",
    title: "V03 局部机械不变量证据",
    owner: "M08",
    maturity: "defined",
    definition: { file: "testing/acceptance-matrix.md", anchor: "V03" },
  },
  V04: {
    kind: "evidence",
    name: "composition-cases",
    title: "V04 跨组件交接与生产入口证据",
    owner: "M08",
    maturity: "defined",
    definition: { file: "testing/acceptance-matrix.md", anchor: "V04" },
  },
  V05: {
    kind: "evidence",
    name: "protocol-and-endpoint",
    title: "V05 协议兼容与真实端点证据",
    owner: "M04",
    maturity: "defined",
    definition: { file: "testing/acceptance-matrix.md", anchor: "V05" },
  },
  V06: {
    kind: "evidence",
    name: "semantic-quality",
    title: "V06 语义质量证据与人工抽检",
    owner: "E03",
    maturity: "defined",
    definition: { file: "testing/acceptance-matrix.md", anchor: "V06" },
  },
  V07: {
    kind: "evidence",
    name: "ui-and-diagnostics",
    title: "V07 界面交互与诊断可定位性证据",
    owner: "M09",
    maturity: "defined",
    definition: { file: "testing/acceptance-matrix.md", anchor: "V07" },
  },
  V08: {
    kind: "evidence",
    name: "evidence-records",
    title: "V08 证据记录、绑定与当前适用性",
    owner: "M09",
    maturity: "defined",
    definition: { file: "testing/evidence.md", anchor: "V08" },
  },

  // ── D01–D05 依赖单元与工作包 ──────────────────────────────
  D01: {
    kind: "work",
    name: "d0-trustworthy-baseline",
    title: "D01 建立可信基线与最小诊断",
    owner: "M09",
    maturity: "defined",
    definition: {
      file: "implementation/D01-trustworthy-baseline.md",
      anchor: "D01",
    },
    work: { state: "done" },
    implementation: { state: "present" },
    verification: { state: "passed" },
    scope: [
      "N01",
      "N15",
      "N18",
      "Q01",
      "Q03",
      "Q09",
      "Q11",
      "Q12",
      "Q18",
      "G04",
    ],
    depends_on: ["P01", "P02", "P03", "P06", "K17", "V01", "V08"],
    closes: ["G04", "Q18", "Q01"],
  },
  D02: {
    kind: "work",
    name: "d1-protocol-and-recovery",
    title: "D02 修正协议与有界纠偏",
    owner: "C14",
    maturity: "defined",
    definition: {
      file: "implementation/D02-protocol-and-recovery.md",
      anchor: "D02",
    },
    work: { state: "done" },
    implementation: { state: "present" },
    verification: { state: "passed" },
    scope: ["N01", "N15", "N16", "N17", "N20", "N21", "Q04", "Q10", "G06"],
    depends_on: ["D01", "K04", "K06", "K10", "K15", "K16", "R11", "R12"],
    closes: ["Q04", "Q10", "G06"],
    note: "2026-09-19 收口：D02 自身有 current verify，关闭门槛三行各有对应记录（Q04／Q10 用现有 V03，G06 用 host_authority 独立命令），§三之一记时点，故 work.state=done、verification.state=passed——只表示本包清单已绑定，不代标 C11／C14 的 passed，也不表示逐端点 V05 已通过（外移 G03／Q17／D04）。Q13 不关。",
  },
  D03: {
    kind: "work",
    name: "d2-session-permission-context",
    title: "D03 收清会话、权限与上下文",
    owner: "C07",
    maturity: "defined",
    definition: {
      file: "implementation/D03-session-permission-context.md",
      anchor: "D03",
    },
    work: { state: "done" },
    implementation: { state: "present" },
    verification: { state: "passed" },
    // Q15／Q16 于 2026-09-19 确定并关闭，据此移出 scope：它们不再是本包「尚未收清」的
    // 范围。
    //
    // `closes` 是 D03 **自身宣布关闭**的项，保持 ["Q08","G05"] 不动。Q02／G01 虽由本包
    // 施工修复并作为证据绑定，但它们的 `blocks` 边指向本包验收；先宣布 closes、再写证据，
    // 等于用声明换豁免（D02 收口时明确禁止的顺序）。因此它们在 scope 内、不在 closes 内，
    // 由 `registry.issues` 在验收时独立写 closed。
    scope: ["N05", "N12", "N13", "N14", "N22", "Q02", "Q08", "G01", "G05"],
    depends_on: ["D01", "K01", "K03", "K05", "K07", "K08"],
    closes: ["Q08", "G05"],
    note: "2026-09-19 收口：Q02／G01 由本包施工修复并绑证据，Q08／G05 由本包关闭；D03 自身有 current verify，§三之一 记时点。verification.state=passed 只表示本包清单已绑定，不代标 C03／C07／C08 等组件的 passed。",
  },
  D04: {
    kind: "work",
    name: "d3-dual-path-search",
    title: "D04 接通双路搜索完整链路",
    owner: "C20",
    maturity: "defined",
    definition: {
      file: "implementation/D04-dual-path-search.md",
      anchor: "D04",
    },
    work: { state: "planned" },
    scope: [
      "N06",
      "N07",
      "N08",
      "N09",
      "N10",
      "N11",
      "N19",
      "Q02",
      "Q05",
      "Q17",
      "G02",
      "G03",
    ],
    depends_on: ["D02", "D03", "K09", "K11", "K12", "K13", "K14", "K18"],
    closes: ["Q02", "Q05", "Q17", "G02", "G03"],
  },
  D05: {
    kind: "work",
    name: "d4-document-tasks-and-delivery",
    title: "D05 贯通文档任务与最终交付",
    owner: "C23",
    maturity: "defined",
    definition: {
      file: "implementation/D05-document-tasks-and-delivery.md",
      anchor: "D05",
    },
    work: { state: "planned" },
    scope: ["N02", "N03", "N04", "N11", "N23", "Q14"],
    depends_on: ["D02", "D03", "K05", "K15", "K16", "L03", "L04"],
  },
  D06: {
    kind: "work",
    name: "d5-calibration-and-delegation",
    title: "D06 校准整体行为及可选委派",
    owner: "C15",
    maturity: "defined",
    definition: { file: "tests/legacy-batch-plan.md", anchor: "D06" },
    work: { state: "planned" },
    scope: ["N16", "N18", "Q06", "Q07", "Q19"],
    depends_on: ["D04", "D05", "V06", "E03"],
  },

  // ── R01–R13 决定记录 ───────────────────────────────────────
  R01: {
    kind: "decision",
    name: "adopt-architecture-definition",
    title: "R01 采用架构定义的 9 模块 27 组件",
    owner: "M01",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R01" },
  },
  R02: {
    kind: "decision",
    name: "keep-runtime-rewrite-gateway",
    title: "R02 保留运行底座、局部评估成熟协议实现",
    owner: "M04",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R02" },
  },
  R03: {
    kind: "decision",
    name: "dual-path-single-tool",
    title: "R03 单一搜索接口、两条内部路线",
    owner: "M07",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R03" },
  },
  R04: {
    kind: "decision",
    name: "native-search-isolated-subrequest",
    title: "R04 原生搜索隔离为受控子请求",
    owner: "M04",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R04" },
  },
  R05: {
    kind: "decision",
    name: "input-revision-at-safe-point",
    title: "R05 输入修订在安全点生效",
    owner: "M01",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R05" },
  },
  R06: {
    kind: "decision",
    name: "verification-separate-from-delivery",
    title: "R06 验证与交付分离",
    owner: "M08",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R06" },
  },
  R07: {
    kind: "decision",
    name: "diagnostics-independent-module",
    title: "R07 诊断独立设模块",
    owner: "M09",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R07" },
  },
  R08: {
    kind: "decision",
    name: "recoverable-errors-are-corrected",
    title: "R08 可恢复错误先反馈再纠偏",
    owner: "M05",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R08" },
  },
  R09: {
    kind: "decision",
    name: "no-second-authority-state",
    title: "R09 不并行运行两套权威状态",
    owner: "M01",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R09" },
  },
  R10: {
    kind: "decision",
    name: "deterministic-tests-do-not-prove-quality",
    title: "R10 确定性测试不替代真实质量评价",
    owner: "E03",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R10" },
  },
  R11: {
    kind: "decision",
    name: "constraint-layers-model-owns-next-action",
    title: "R11 约束分不变量／信封／配方，模型拥有下一步",
    owner: "M05",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R11" },
  },
  R12: {
    kind: "decision",
    name: "completion-reserve-is-output-cap-envelope",
    title: "R12 完成额度预留是输出帽信封，不是关面配方",
    owner: "M05",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R12" },
  },

  R13: {
    kind: "decision",
    name: "same-schema-budget-drift-schema-gate-deferred-table",
    title: "R13 改预算默认值必须先升 schema_version（已采用；常量表延后）",
    owner: "M05",
    maturity: "defined",
    definition: { file: "decisions/README.md", anchor: "R13" },
    consumes: ["K06"],
    note: "已采用：当前不改默认值；改数必须先升 schema_version。常量表延后到第一次改数。不关闭 Q13，不把 D02 标为可验收。",
  },

  // ── Q01–Q19 / G01–G06 未决问题与缺口 ──────────────────────
  Q01: {
    kind: "issue",
    title: "历史未知工具提议无法事后唯一归因",
    owner: "M09",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q01" },
    blocks: blocks("acceptance", ["D01"]),
    note: "调查结论：2026-09-14 那次无法唯一归因；同类现象的可定位性由 D01 交付。不阻断 D02。",
  },
  Q02: {
    kind: "issue",
    title: "两个设置入口的 MCP 搜索候选写入语义不一致",
    owner: "M06",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q02" },
    blocks: blocks("acceptance", ["D03", "D04"]),
  },
  Q03: {
    kind: "issue",
    title: "评测空分母被记为满分",
    owner: "E03",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q03" },
    blocks: blocks("acceptance", ["D01", "D06"]),
  },
  Q04: {
    kind: "issue",
    title: "Chat Completions 流式终止原因丢失",
    owner: "M04",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q04" },
    blocks: blocks("acceptance", ["D02"]),
    note: "关闭门槛：Chat Completions 五类终止的现有 V03 机械记录（4 条）即关闭证据；逐端点 V05 外移 G03／Q17／D04，不是本条关闭条件。Anthropic 五类只算 C11／K04，不扩大本条。",
  },
  Q05: {
    kind: "issue",
    title: "读取路径写入数据库触发隐藏配置变更",
    owner: "M06",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q05" },
    blocks: blocks("acceptance", ["D04"]),
    note: "落点 058366ea；源码 list 只读已有机械 V03；关闭仍等 D04 验收。不把 C18 verification 标为通过。",
  },
  Q06: {
    kind: "issue",
    title: "子任务 context_hint／max_rounds 未被消费",
    owner: "M05",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q06" },
    blocks: blocks("acceptance", ["D06"]),
  },
  Q07: {
    kind: "issue",
    title: "子工具缺少标准网页正文抓取",
    owner: "M05",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q07" },
    blocks: blocks("acceptance", ["D06"]),
  },
  Q08: {
    kind: "issue",
    title: "压缩覆盖边界与裁剪边界不同源",
    owner: "M03",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q08" },
    blocks: blocks("acceptance", ["D03"]),
  },
  Q09: {
    kind: "issue",
    title: "诊断关联不完整",
    owner: "M09",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q09" },
    blocks: blocks("acceptance", ["D01"]),
  },
  Q10: {
    kind: "issue",
    title: "模型协议字段丢失与续轮保真",
    owner: "M04",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q10" },
    blocks: blocks("acceptance", ["D02"]),
    note: "关闭门槛：事实 1–3 的现有 V03 机械记录（5 条）即关闭证据；逐端点 V05 外移 G03／Q17／D04。服务端搜索事件与引用不算本条（→ G03）。",
  },
  Q11: {
    kind: "issue",
    title: "部分确定性测试与实现共享同一错误假设",
    owner: "E03",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q11" },
    blocks: blocks("acceptance", ["D01", "D06"]),
  },
  Q12: {
    kind: "issue",
    title: "历史诊断不足以区分工具名来源",
    owner: "M09",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q12" },
    blocks: blocks("acceptance", ["D01"]),
  },
  Q13: {
    kind: "issue",
    title: "预算存档兼容：同版本不同数值可能读取失败",
    owner: "M05",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q13" },
    note: "R13 已采用（改数必须先升 schema）。仍 open。不阻断 D02；第一次改 for_profile 默认值的施工被本条挡住，届时再挂 blocks。不得把「风险尚未发生」或移出 D02 写成已关闭。",
  },
  Q14: {
    kind: "issue",
    title: "双路搜索对纯编辑任务的触发范围未单独确认",
    owner: "M07",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q14" },
    blocks: blocks("acceptance", ["D05"]),
  },
  Q15: {
    kind: "issue",
    title: "长期记忆的写入时机、有效期与冲突管理未确定",
    owner: "M03",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q15" },
    note: "2026-09-19 关闭：写入只能由 memory_write 显式发起且需确认、默认不自动把聊天写成事实、作用域 global／vault、clear_scope 不越界；**有效期与冲突呈现明确不实现**（表无过期列、无冲突裁决界面），需要单独的功能决定与工作包。blocks 边与 D03／D05 的 scope 一并移出，不再阻断验收。",
  },
  Q16: {
    kind: "issue",
    title: "运行中追加／修改指令的交互未确定",
    owner: "M01",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q16" },
    note: "2026-09-19 交互形态确定并关闭：Host 在 Run 进行中拒绝新指令（agent_run_active_run_exists），用户等待、取消或完成后重发；两条性质（取消不启动新副作用、未发布候选不得发布）各有绑定证据，形态写入 K03 §一。blocks 边与 D03 scope 一并移出——本条不再阻断 D03 验收。关闭是「选择已作出」，不是「运行中修订已实现」。",
  },
  Q17: {
    kind: "issue",
    title: "原生搜索端点与混合续轮适配待验证",
    owner: "M04",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q17" },
    blocks: blocks("acceptance", ["D04"]),
    note: "V05 承接方（2026-09-17）：Q04／Q10 的关闭不再要求逐端点 V05，该证据由本条与 G03／D04 承接。D02 不关闭本条。",
  },
  Q18: {
    kind: "issue",
    title: "缺少出站请求的安全结构证据",
    owner: "M09",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q18" },
    blocks: blocks("acceptance", ["D01"]),
  },
  Q19: {
    kind: "issue",
    title: "网络额度是否为主要瓶颈待验证",
    owner: "M05",
    maturity: "draft",
    definition: { file: "requirements/current-baseline.md", anchor: "Q19" },
    blocks: blocks("acceptance", ["D06"]),
  },
  G01: {
    kind: "issue",
    title: "工具目录目标与现状的差异",
    owner: "M06",
    maturity: "draft",
    definition: { file: "requirements/open-items.md", anchor: "G01" },
    blocks: blocks("acceptance", ["D03", "D05"]),
  },
  G02: {
    kind: "issue",
    title: "双路搜索协调的真实执行",
    owner: "M07",
    maturity: "draft",
    definition: { file: "requirements/open-items.md", anchor: "G02" },
    blocks: blocks("acceptance", ["D04"]),
    note: "两已登记模型 Available 时会发起原生+MCP。机械 V03 不是验收；不关本条，不把两个替身写成 V04，不把 MCP 主备写成双路。现状见 open-items G02。",
  },
  G03: {
    kind: "issue",
    title: "原生搜索事件的接入与端点适配",
    owner: "M04",
    maturity: "draft",
    definition: { file: "requirements/open-items.md", anchor: "G03" },
    blocks: blocks("acceptance", ["D04"]),
    note: "适配器已登记两模型；流式主路径仍未保真搜索事件。不是关闭，不是 V05。D02 不关闭本条。",
  },
  G04: {
    kind: "issue",
    title: "出站结构诊断与完整关联",
    owner: "M09",
    maturity: "draft",
    definition: { file: "requirements/open-items.md", anchor: "G04" },
    blocks: blocks("acceptance", ["D01"]),
  },
  G05: {
    kind: "issue",
    title: "运行中输入修订与压缩覆盖一致性",
    owner: "M03",
    maturity: "draft",
    definition: { file: "requirements/open-items.md", anchor: "G05" },
    blocks: blocks("acceptance", ["D03"]),
  },
  G06: {
    kind: "issue",
    title: "Host 用配方当第二规划器",
    owner: "M05",
    maturity: "draft",
    definition: { file: "requirements/open-items.md", anchor: "G06" },
    blocks: blocks("acceptance", ["D02"]),
    note: "关闭门槛：过早收束负例由 host_authority 的独立 verify 命令绑定（agent_tool_loop_host_authority_tests.rs），不写在 C14 备注里代替。字段级 mismatch（K16／C14）与 Anthropic 终止（C11／K04）不写入本条关闭条件。随 D02 验收关闭。",
  },

  // ── X01–X03 检查器与基础设施 ──────────────────────────────
  X01: {
    kind: "test",
    name: "agent-harness-check",
    title: "X01 文档体系检查器",
    owner: "P03",
    maturity: "defined",
    definition: { file: "rules/governance.md", anchor: "X01" },
    verification: { state: "passed" },
    implements: ["P02", "P03"],
  },
  X02: {
    kind: "test",
    name: "agent-harness-check-self-test",
    title: "X02 检查器负例自测",
    owner: "P03",
    maturity: "defined",
    definition: { file: "rules/governance.md", anchor: "X02" },
    verification: { state: "passed" },
    verifies: ["X01", "P02", "P03"],
    depends_on: ["X01"],
  },
  X03: {
    kind: "test",
    name: "registry",
    title: "X03 登记表",
    owner: "P03",
    maturity: "defined",
    definition: { file: "rules/governance.md", anchor: "X03" },
    consumes: ["P01", "P02", "P03", "P04", "P05", "P06", "P07"],
    note: "身份、定义位置、修订与指纹、类型化关系、决定与复核记录；由 --reconcile 写入计算结果",
  },
};

/**
 * 工具 ID → 工具名。工具卡文件名由名称派生：tools/<name>.md。
 * 语义归属与目标合同见 docs/agent-architecture.md §6.2、§6.3。
 */
export const tools = {
  T01: "system_time_now",
  T02: "app_context_read",
  T03: "capabilities_read",
  T04: "skills_list",
  T05: "search_hybrid",
  T06: "read_note",
  T07: "list_vault",
  T08: "get_outline",
  T09: "get_backlinks",
  T10: "get_context_packets",
  T11: "web_search",
  T12: "web_fetch",
  T13: "memory_read",
  T14: "memory_write",
  T15: "insert_text_at_cursor",
  T16: "replace_selection",
  T17: "git_read_status",
  T18: "git_read_diff",
  T19: "git_read_log",
  T20: "secret_exists",
  T21: "fs_import_to_vault",
  T22: "fs_export",
  T23: "fs_read_authorized_folder",
  T24: "fs_write_authorized_export",
  T25: "doc_normalize_markdown",
  T26: "doc_extract_citations",
  T27: "git_write_commit",
  T28: "search_semantic",
  T29: "search_keyword",
  T30: "get_regulation",
  T31: "spawn_subagent",
  T32: "scheduled_task_create",
  T33: "scheduled_task_list",
  T34: "scheduled_task_delete",
  T35: "vault_create_note",
  T36: "vault_rename_move",
  T37: "vault_delete_to_trash",
  T38: "vault_asset_write",
  T39: "vault_version_list",
};

/** 工具语义归属、暴露规则与是否属于通用能力目录（16 个）。 */
export const toolPlacement = {
  T01: { owner: "M06", surface: "general" },
  T02: { owner: "M01", surface: "general" },
  T03: { owner: "M06", surface: "general" },
  T04: { owner: "M06", surface: "general" },
  T05: { owner: "M07", surface: "general" },
  T06: { owner: "M06", surface: "general" },
  T07: { owner: "M06", surface: "general" },
  T08: { owner: "M06", surface: "general" },
  T09: { owner: "M06", surface: "general" },
  T10: { owner: "M03", surface: "general" },
  T11: { owner: "M07", surface: "general" },
  T12: { owner: "M07", surface: "general" },
  T13: { owner: "M03", surface: "general" },
  T14: { owner: "M02", surface: "general" },
  T15: { owner: "M02", surface: "general" },
  T16: { owner: "M02", surface: "general" },
  T17: { owner: "M06", surface: "extended" },
  T18: { owner: "M06", surface: "extended" },
  T19: { owner: "M06", surface: "extended" },
  T20: { owner: "M06", surface: "extended" },
  T21: { owner: "M02", surface: "extended" },
  T22: { owner: "M02", surface: "extended" },
  T23: { owner: "M06", surface: "extended" },
  T24: { owner: "M02", surface: "extended" },
  T25: { owner: "M08", surface: "extended" },
  T26: { owner: "M07", surface: "extended" },
  T27: { owner: "M02", surface: "extended" },
  T28: { owner: "M07", surface: "extended" },
  T29: { owner: "M07", surface: "extended" },
  T30: { owner: "M07", surface: "extended" },
  T31: { owner: "M05", surface: "extended" },
  T32: { owner: "M02", surface: "extended" },
  T33: { owner: "M06", surface: "extended" },
  T34: { owner: "M02", surface: "extended" },
  T35: { owner: "M02", surface: "extended" },
  T36: { owner: "M02", surface: "extended" },
  T37: { owner: "M02", surface: "extended" },
  T38: { owner: "M02", surface: "extended" },
  T39: { owner: "M06", surface: "extended" },
};

/**
 * 工具卡的当前状态。语义归属见 docs/agent-architecture.md §6.2、§6.3；
 * `implementation.state` 只描述源码事实，不代表合同正确或用户任务可用。
 * Planned 占位（11 个）不分配工具 ID，见 tools/README.md。
 */
const toolState = {
  T01: "present",
  T02: "present",
  T03: "partial",
  T04: "present",
  T05: "present",
  T06: "present",
  T07: "present",
  T08: "present",
  T09: "present",
  T10: "present",
  T11: "partial",
  T12: "present",
  T13: "present",
  T14: "present",
  T15: "present",
  T16: "present",
  T17: "present",
  T18: "present",
  T19: "present",
  T20: "present",
  T21: "present",
  T22: "present",
  T23: "present",
  T24: "present",
  T25: "present",
  T26: "present",
  T27: "present",
  T28: "present",
  T29: "present",
  T30: "present",
  T31: "partial",
  T32: "present",
  T33: "present",
  T34: "present",
  T35: "present",
  T36: "present",
  T37: "present",
  T38: "present",
  T39: "present",
};

/** 工具卡消费的合同（implements/consumes 关系来源，供检查器核对）。 */
const toolContracts = {
  T01: { consumes: [] },
  T02: { consumes: ["K01", "K05"] },
  T03: { consumes: ["K10"] },
  T04: { consumes: ["K10"] },
  T05: { consumes: ["K09"] },
  T06: { consumes: ["K05", "K14"] },
  T07: { consumes: ["K05"] },
  T08: { consumes: ["K05"] },
  T09: { consumes: ["K05"] },
  T10: { consumes: ["K07"] },
  T11: { consumes: ["K09", "K11", "K12"] },
  T12: { consumes: ["K09", "K13"] },
  T13: { consumes: ["K05", "K08"] },
  T14: { consumes: ["K05", "K08"] },
  T15: { consumes: ["K05", "K14"] },
  T16: { consumes: ["K05", "K14"] },
  T17: { consumes: ["K05"] },
  T18: { consumes: ["K05"] },
  T19: { consumes: ["K05"] },
  T20: { consumes: ["K05"] },
  T21: { consumes: ["K05"] },
  T22: { consumes: ["K05"] },
  T23: { consumes: ["K05"] },
  T24: { consumes: ["K05"] },
  T25: { consumes: ["K16"] },
  T26: { consumes: ["K14"] },
  T27: { consumes: ["K05"] },
  T28: { consumes: ["K09"] },
  T29: { consumes: ["K09"] },
  T30: { consumes: ["K09"] },
  T31: { consumes: ["K06", "K10", "K14"] },
  T32: { consumes: ["K05"] },
  T33: { consumes: ["K05"] },
  T34: { consumes: ["K05"] },
  T35: { consumes: ["K05"] },
  T36: { consumes: ["K05"] },
  T37: { consumes: ["K05"] },
  T38: { consumes: ["K05"] },
  T39: { consumes: ["K05"] },
};

/**
 * 需求对象 N01–N23（见 requirements/requirements.md）。
 * 需求是「要求」而不是实现：它们被实现对象 implements／被测试 verifies，
 * 工作包用 scope 引用它们证明自己有需求依据。
 */
const requirementPlacement = {
  N01: { title: "基础对话、话题切换、追问与纠正可靠", owner: "M01" },
  N02: { title: "字词／句段润色、扩写与缩写", owner: "M08" },
  N03: { title: "按目标格式与文风生成内容，由用户插入", owner: "M08" },
  N04: { title: "Markdown 格式整理不修改实际内容（序号除外）", owner: "M08" },
  N05: { title: "自然连续对话承接前文、指代与纠正", owner: "M03" },
  N06: { title: "联网查询与后续核实", owner: "M07" },
  N07: { title: "原生与 MCP 两路都实际搜索", owner: "M07" },
  N08: { title: "两路 URL 均可由 MCP 抓取，按需读取", owner: "M07" },
  N09: { title: "不支持原生搜索时正常单 MCP，不显示降级", owner: "M04" },
  N10: { title: "分路失败保留另一路结果并分别记录", owner: "M07" },
  N11: { title: "所有路径失败时如实说明无法核实", owner: "M08" },
  N12: { title: "严格场景保留联网限制，授权覆盖重试与子任务", owner: "M02" },
  N13: { title: "外发边界与双路冲突时先满足已授权数据边界", owner: "M02" },
  N14: { title: "长对话压缩、记忆与最新约束承接", owner: "M03" },
  N15: { title: "LOOP：持续行动、验证、纠错直到完成", owner: "M05" },
  N16: { title: "容错纠偏：可恢复错误不得一次即终止", owner: "M05" },
  N17: { title: "不得因单次工具错误提示模型能力降级", owner: "M08" },
  N18: { title: "审计覆盖模块、组件、工具与模型行为并可定位", owner: "M09" },
  N19: { title: "免费工具与自付费服务并存", owner: "M06" },
  N20: { title: "MiniMax／DeepSeek 为主模型并兼顾国产模型", owner: "M04" },
  N21: {
    title: "观察后信封允许时模型仍可再提议；多步是语义不是清单",
    owner: "M05",
  },
  N22: {
    title: "普通研究 Run 不承诺进程续跑；仅 Durable 有检查点",
    owner: "M01",
  },
  N23: {
    title: "撤回已发布答案不等于 Host 在循环内重规划",
    owner: "M08",
  },
};

for (const [id, entry] of Object.entries(requirementPlacement)) {
  objects[id] = {
    kind: "requirement",
    name: id,
    title: entry.title,
    owner: entry.owner,
    maturity: "draft",
    definition: { file: "requirements/requirements.md", anchor: id },
    note: "需求条目；来源与承接对象见 requirements/requirements.md",
  };
}

/**
 * 文件级容器对象。ID 由文件路径派生（见 rules/objects.md §2.3），
 * 承接文件前言与所有子对象块之外的正文；它的指纹变化会使该文件内的子对象进入复核。
 * 容器对象不是正式定义，maturity 固定为 draft。
 */
// 多对象文件（评测系统、决定记录、施工目录索引）需要独立的容器条目；
// 单对象文件的容器与对象同 ID，由该对象自己的条目承担，这里不重复登记。
const multiObjectContainers = {
  "modules/eval-system.md": "FILE-EVAL-SYSTEM",
  "decisions/README.md": "FILE-DECISIONS",
  "implementation/README.md": "FILE-IMPLEMENTATION",
};
for (const [rel, containerId] of Object.entries(multiObjectContainers)) {
  objects[containerId] = {
    kind: "rules",
    name: containerId,
    title: `${rel} 的文件级容器`,
    owner: "P03",
    maturity: "draft",
    definition: { file: rel, anchor: containerId },
    note: "多对象文件的容器：承接前言与外围正文，不承载对象正式定义",
  };
}

for (const [id, name] of Object.entries(tools)) {
  objects[id] = {
    kind: "tool",
    name,
    title: name,
    owner: toolPlacement[id].owner,
    maturity: "draft",
    definition: { file: `tools/${name}.md`, anchor: id },
    implementation: { state: toolState[id] },
    verification: { state: "none" },
    consumes: toolContracts[id].consumes,
    note: `工具卡；语义归属 ${toolPlacement[id].owner}，暴露面 ${toolPlacement[id].surface}`,
  };
}

/** 工具卡工具名 → ID（反向索引，避免两处手写）。 */
export const toolIdByName = Object.fromEntries(
  Object.entries(tools).map(([id, name]) => [name, id]),
);
